services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      AWS_REGION: eu-north-1
      READINGS_TABLE: Readings
      ALERTS_TABLE: Alerts
      S3_BUCKET: healthcare-project-exports

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend